/* ZoodoGreen V1: local-first state; replace storage adapters with an API when authentication is added. */
const LEVELS = [
  { level: 1, minXp: 0 }, { level: 2, minXp: 100 }, { level: 3, minXp: 250 }, { level: 4, minXp: 500 }, { level: 5, minXp: 900 }
];
const WASTES = [
  ['♻️', 'Déchets plastiques', 'Bouteilles, sachets et emballages.', 'Dans un point de collecte ou bac recyclage propre et sec.', 'Ils mettent des siècles à disparaître et polluent les sols et l’eau.'],
  ['🍌', 'Déchets organiques', 'Épluchures, restes de repas et feuilles.', 'Au compost ou dans le bac à déchets organiques.', 'Ils deviennent un compost utile pour les plantations.'],
  ['📦', 'Papier et carton', 'Cahiers, journaux, boîtes et cartons.', 'Dans le bac papier, propres et pliés.', 'Le recyclage évite de couper inutilement des arbres.'],
  ['🍾', 'Verre', 'Bocaux, pots et bouteilles en verre.', 'Dans une borne à verre, sans bouchon.', 'Le verre est recyclable encore et encore.'],
  ['🔌', 'Déchets électroniques', 'Téléphones, piles, chargeurs et écouteurs.', 'Dans un point de collecte spécialisé, jamais dans la rue.', 'Ils contiennent des matières précieuses et parfois toxiques.'],
  ['⚠️', 'Déchets dangereux', 'Produits chimiques, médicaments, ampoules.', 'Dans une collecte dédiée ou chez un professionnel.', 'Ils peuvent contaminer l’eau et blesser les personnes.']
];
const QUIZ = [
  { q: 'Une bouteille en plastique vide va…', a: ['Dans la rue', 'Dans un point de collecte plastique', 'Avec les déchets dangereux'], correct: 1, why: 'Bien vidée, elle peut être triée puis recyclée.' },
  { q: 'Les épluchures de mangue sont…', a: ['Des déchets organiques', 'Des déchets électroniques', 'Du verre'], correct: 0, why: 'Elles peuvent devenir du compost pour nourrir les plantes.' },
  { q: 'Que faire d’une pile usagée ?', a: ['La jeter avec les ordures', 'La brûler', 'La déposer dans un point de collecte'], correct: 2, why: 'Une pile contient des substances qui ne doivent pas finir dans les sols.' },
  { q: 'Pourquoi trier le papier ?', a: ['Pour recycler les fibres', 'Parce qu’il disparaît en un jour', 'Pour le mélanger au verre'], correct: 0, why: 'Les fibres du papier peuvent avoir une nouvelle vie.' }
];
const CHALLENGES = [
  { id:'sort7', icon:'🗓️', title:'Trier pendant 7 jours', text:'Sépare tes déchets chaque jour pendant une semaine.', xp:60 },
  { id:'bottle', icon:'💧', title:'Une journée sans bouteille plastique', text:'Prends une gourde réutilisable pour la journée.', xp:30 },
  { id:'clean10', icon:'🧤', title:'10 déchets dans mon quartier', text:'Ramasse 10 déchets en toute sécurité avec des gants.', xp:45 }
];
const USERS = [['Aïcha K.', 580, '🌻'], ['Issa_226', 520, '🦁'], ['MariamG', 470, '🌿'], ['Fatou.bf', 420, '🌺'], ['Ousmane', 390, '🛹']];
const app = document.querySelector('#app');
let state = JSON.parse(localStorage.getItem('zoodogreen-state') || '{"xp":70,"completed":[],"route":"home"}');
let quizIndex = 0, quizScore = 0, answered = false;
const save = () => localStorage.setItem('zoodogreen-state', JSON.stringify(state));
const levelInfo = () => { const current = [...LEVELS].reverse().find(l => state.xp >= l.minXp) || LEVELS[0]; const next = LEVELS.find(l => l.minXp > state.xp); return { current, next, percent: next ? Math.min(100, ((state.xp-current.minXp)/(next.minXp-current.minXp))*100) : 100 }; };
const nav = () => `<nav class="bottom-nav" aria-label="Navigation principale">${[['home','⌂','Accueil'],['learn','◈','Apprendre'],['quiz','✦','Quiz'],['challenges','✓','Défis'],['leaderboard','☷','Classement'],['profile','☺','Profil']].map(([id,icon,label]) => `<button class="nav-item ${state.route===id?'active':''}" data-route="${id}" aria-label="${label}"><i>${icon}</i>${label}</button>`).join('')}</nav><div id="toast" class="toast"></div>`;
const header = (title, intro) => `<h1 class="page-title">${title}</h1><p class="intro">${intro}</p>`;
function renderHome() { return `<section class="page hero"><div class="brand"><span class="brand-mark">◔</span>Zoodo<span style="color:var(--green)">Green</span></div><p class="eyebrow">Apprendre • Agir • Inspirer</p><h1>Ensemble pour un Burkina plus vert.</h1><p>Des gestes simples, des défis concrets et une communauté qui avance dans la même direction.</p><div class="hero-art" aria-hidden="true"><div class="sun"></div><div class="leaf">🌿</div><div class="hill"></div><div class="hill two"></div></div><button class="primary" data-route="learn">Commencer à apprendre →</button><div class="stats"><div class="stat"><strong>2 450</strong><span>jeunes engagés</span></div><div class="stat"><strong>1,2 t</strong><span>déchets triés</span></div><div class="stat"><strong>860</strong><span>défis réalisés</span></div></div></section>`; }
function renderLearn() { return `<section class="page">${header('Apprendre à trier', 'Des repères simples pour faire le bon geste, où que tu sois.')}<div class="learn-grid">${WASTES.map((w,i) => `<button class="learn-card" data-waste="${i}"><span class="waste-icon">${w[0]}</span><span><h3>${w[1]}</h3><p>${w[2]}</p><p class="tag">Voir le guide →</p></span></button>`).join('')}</div><div id="waste-detail"></div></section>`; }
function renderQuiz() { const li=levelInfo(); if (quizIndex >= QUIZ.length) return `<section class="page">${header('Quiz terminé !', `Tu as obtenu ${quizScore} XP sur ${QUIZ.length*20}.`)}<div class="quiz-card" style="text-align:center"><div style="font-size:50px">${quizScore >= 60?'🏆':'🌱'}</div><h2>${quizScore >= 60?'Bravo, champion·ne !':'Belle progression !'}</h2><p class="intro">Chaque réponse te rapproche d’un Burkina plus propre.</p><button class="primary" id="restart-quiz">Recommencer le quiz</button></div></section>`; return `<section class="page">${header('Le quiz vert', 'Teste tes réflexes et gagne 20 XP par bonne réponse.')}<div class="xp-card"><div class="xp-row"><span>Ton niveau ${li.current.level}</span><strong>${state.xp} XP</strong></div><div class="progress"><span style="width:${li.percent}%"></span></div><span class="small">${li.next ? `${li.next.minXp-state.xp} XP avant le niveau ${li.next.level}` : 'Niveau maximum atteint'}</span></div><div class="quiz-card"><span class="quiz-number">QUESTION ${quizIndex+1} / ${QUIZ.length}</span><h2 class="quiz-question">${QUIZ[quizIndex].q}</h2><div>${QUIZ[quizIndex].a.map((answer,i) => `<button class="answer" data-answer="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}. ${answer}</button>`).join('')}</div><div id="feedback-area"></div></div></section>`; }
function renderChallenges() { return `<section class="page">${header('Défis du moment', 'Passe à l’action à ton rythme. Chaque geste compte.')}<div>${CHALLENGES.map(c => { const done=state.completed.includes(c.id); return `<article class="challenge ${done?'done':''}"><div class="challenge-top"><div class="challenge-icon">${done?'✓':c.icon}</div><div><h3>${c.title}</h3><p>${c.text}</p></div></div><footer><span class="xp-pill">+${c.xp} XP</span>${done?'<span class="complete">Terminé ✓</span>':`<button class="complete" data-challenge="${c.id}">Valider le défi</button>`}</footer></article>`; }).join('')}</div></section>`; }
function renderProfile() { const li=levelInfo(); return `<section class="page">${header('Mon profil', 'Ta progression fait grandir le mouvement.')}<div class="profile-head"><div class="profile-avatar">🌍</div><div><h2>Brice Vert</h2><p>Niveau ${li.current.level} · Membre ZoodoGreen</p></div></div><div class="xp-card"><div class="xp-row"><span>Progression</span><strong>${state.xp} XP</strong></div><div class="progress"><span style="width:${li.percent}%"></span></div><span class="small">${li.next ? `${li.next.minXp-state.xp} XP avant le niveau ${li.next.level}` : 'Niveau maximum atteint'}</span></div><h2 class="section-title">Mes badges</h2><div class="badges"><div class="badge"><strong>🌱</strong>Premier pas</div><div class="badge"><strong>${state.completed.length?'🏅':'🔒'}</strong>Défi relevé</div><div class="badge"><strong>♻️</strong>Éco-curieux</div></div><h2 class="section-title">Mes actions</h2><div class="profile-stats"><div><strong>${state.completed.length}</strong><span>défis terminés</span></div><div><strong>${Math.floor(state.xp/20)}</strong><span>bonnes réponses</span></div></div></section>`; }
function renderLeaderboard() { return `<section class="page">${header('Classement', 'La communauté ZoodoGreen avance ensemble.')}<div class="notice">Ces données sont une démo locale. Elles pourront être reliées à une base de données et à des comptes utilisateurs.</div><h2 class="section-title">Cette semaine</h2><div class="leaderboard">${USERS.map((u,i)=>`<div class="rank"><span class="rank-number">${i+1}</span><div class="avatar">${u[2]}</div><div class="rank-name"><b>${u[0]}</b><span>Niveau ${[4,4,3,3,3][i]}</span></div><span class="rank-xp">${u[1]} XP</span></div>`).join('')}</div></section>`; }
function render() { const page = {home:renderHome,learn:renderLearn,quiz:renderQuiz,challenges:renderChallenges,profile:renderProfile,leaderboard:renderLeaderboard}[state.route] || renderHome; app.innerHTML = page() + nav(); bind(); }
function bind() { document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{state.route=b.dataset.route; save(); render();})); document.querySelectorAll('[data-waste]').forEach(b=>b.addEventListener('click',()=>showWaste(+b.dataset.waste))); document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(+b.dataset.answer))); document.querySelectorAll('[data-challenge]').forEach(b=>b.addEventListener('click',()=>completeChallenge(b.dataset.challenge))); document.querySelector('#restart-quiz')?.addEventListener('click',()=>{quizIndex=0;quizScore=0;answered=false;render();}); }
function showWaste(i) { const w=WASTES[i]; document.querySelector('#waste-detail').innerHTML=`<article class="detail"><h3>${w[0]} ${w[1]}</h3><div class="detail-row"><b>Où le jeter ?</b><p>${w[3]}</p></div><div class="detail-row"><b>Pourquoi trier ?</b><p>${w[4]}</p></div></article>`; document.querySelector('#waste-detail').scrollIntoView({behavior:'smooth',block:'nearest'}); }
function answer(choice) { if(answered)return; answered=true; const item=QUIZ[quizIndex], good=choice===item.correct; document.querySelectorAll('[data-answer]').forEach(b=>{ const n=+b.dataset.answer; b.classList.add(n===item.correct?'correct':n===choice?'wrong':''); }); if(good){state.xp+=20;quizScore+=20;save(); toast('+20 XP ! Bien joué 🌿');} document.querySelector('#feedback-area').innerHTML=`<p class="feedback">${good?'✓ Bonne réponse !':'Pas tout à fait.'} ${item.why}<br><button class="complete" id="next-question" style="margin-top:9px">${quizIndex===QUIZ.length-1?'Voir mon score':'Question suivante →'}</button></p>`; document.querySelector('#next-question').addEventListener('click',()=>{quizIndex++;answered=false;render();}); }
function completeChallenge(id) { if(state.completed.includes(id))return; const c=CHALLENGES.find(x=>x.id===id); state.completed.push(id);state.xp+=c.xp;save();toast(`Défi validé ! +${c.xp} XP`);render(); }
function toast(message) { const t=document.querySelector('#toast'); if(!t)return; t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400); }
if ('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
render();
